remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  is_project_page: false
title: London Robotics & AI Summer Mini-School
description: <a href="https://arq-crisp.github.io/Robotics-AI-Mini-School/">Main Page</a> | <a href="https://arq-crisp.github.io/Robotics-AI-Mini-School/tasks.html">Tasks</a>
markdown: GFM
